# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        /*
        Add your outputs of this template here, if needed
        Some important Conventions to take in consideration:
        - consideration 1
        - consideration 2
        */
        
output "vpc_id" {
  description = "The ID of the VPC"
  value       = aws_vpc.main.id
}
output "private_subnet_ids" {
  value = join(",", aws_subnet.private.*.id)
}
output "alarm_sns_topic" {
  value = aws_sns_topic.alarm_sns_topic.arn
}       
       
