# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        /*
        Add your outputs of this template here, if needed
        Some important Conventions to take in consideration:
        - consideration 1
        - consideration 2
        */
locals{
        network_information = {
                "${var.region}-vpc" = merge({
                        vpc_name = aws_vpc.main.tags.Name 
                        vpc_cidr = aws_vpc.main.cidr_block 
                        internet_gateway = aws_internet_gateway.gateway.tags.Name
                        route_table = aws_route_table.routetable_internetaccess.tags.Name
                        }, {for value in aws_subnet.private:
                                value.tags.Name => [
                                value.cidr_block,
                                value.availability_zone      
                                ]                 
                        })
                        
                }
        }
output "network" {
  value = local.network_information
}

output "vpc_id" {
  description = "The ID of the VPC"
  value       = aws_vpc.main.id
}
output "private_subnet_ids" {
  value = join(",", aws_subnet.private.*.id)
}
output "alarm_sns_topic" {
  value = aws_sns_topic.alarm_sns_topic.arn
}       
       
