# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        /*
        Add your variables of this template here.
        Some important Conventions to take in consideration:
        - use variable names which are self explanatory 
        */
        
variable "project_prefix" {
  type = string
  description = "Variable comming from the environement"
}
variable "account_short_name"{
  type = string
  description = "the account shortname the network should be deployed in."
}
variable "vpc_cidr"{
  type = string
  description = "the vpc cidr to create a vpc"
}        
        
