# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        /*
        Add your outputs of this template here, if needed
        Some important Conventions to take in consideration:
        - consideration 1
        - consideration 2
        */


locals {
        network_information = [ for value in var.network.default_network.subnets: 
                value
        ]
        # liste alle vms auf als key schreibe deren id, subnet, az, seggroups auf
        vms = [
                ""
        ]
        //input the real variables
        //gib alles raus mit kombinationen von verschiedenen infos zusammengestellt
}   
output "network"{
 value = local.network_information
} 
output "virtual-machines"{
 value = local.vms
} 