# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        /*
        This will ensure that the default profile will be used to login to your aws account.
        Here, you can also mention a custom profile of your liking.
        */
        provider "aws" {}
        
