# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        /*
        Add your variables of this template here.
        Some important Conventions to take in consideration:
        - use variable names which are self explanatory 
        */
        
        
variable "project_prefix" {
  description = "Variable comming from the environement"
}
 
variable "cassandra_instance" {
  type = string
}

variable "key_name"{
  type = string
  description = "Enter a public key name that will be used. This has to be in the AWS Account that you will provision the cassandra db to."
}
variable "region" {
  default = "eu-central-1"
}
variable "golden_image" {
  description = "Enter the ami id of the golden image that you created earlier."
}
variable "vpc_id" {
  description = "The vpc id of which the cassandra db will be deployed."
}
variable "vpc_cidr"{
  type = string
}
variable "alarm_sns_topic" {
 type = string
}

variable "private_subnet_ids" {
 type = list(any)
}
variable "mandatory_tags" {
  type        = map(any)
  description = "Additional tags (e.g. map(`BusinessUnit`,`XYZ`)"
}
variable "network"{
  type = map(object({
                vpc_id = string
                subnets = list(string)
                //security_groups = list(string)
                //nat_gateway_enabled = bool
        }))
/*  default = {"default_network" = {
                vpc_cidr_block = var.vpc_id #"10.0.0.0/16"
                subnets = {#hier eine for schleife fuer output subent
                        "subnet" = {
                                cidr_block = "10.0.1.0/24"
                                availability_zone = "us-west-1a"
                                route_table_id = "rtb-12345"
                        }
                        "subnet2" = {
                                cidr_block = "10.0.2.0/24"
                                availability_zone = "us-west-1b"
                                route_table_id = "rtb-67890"
                        }
                }
                security_groups = ["sg-12345", "sg-67890"]
                nat_gateway_enabled = true
        }
}*/
}

       
